server:
  port: 8000

spring:
  application:
    name: router

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  file: target/${spring.application.name}.log

zuul:
  prefix: /api
  routes:
    customer-service:
      path: /customer/**
      serviceId : customer-service
    product-service:
      path: /product/**
      serviceId: product-service