spring:
  application:
    name: product-service

server:
  port: 8096

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  file: target/${spring.application.name}.log